fix for Codesign

diff --git a/crates/tauri-bundler/src/bundle/macos/dmg/bundle_dmg b/crates/tauri-bundler/src/bundle/macos/dmg/bundle_dmg
--- a/crates/tauri-bundler/src/bundle/macos/dmg/bundle_dmg
+++ b/crates/tauri-bundler/src/bundle/macos/dmg/bundle_dmg
@@ -608,16 +608,21 @@ else
 fi
 
 if [[ -n "${SIGNATURE}" && "${SIGNATURE}" != "-null-" ]]; then
-	echo "Codesign started"
-	codesign -s "${SIGNATURE}" "${DMG_DIR}/${DMG_NAME}"
-	dmgsignaturecheck="$(codesign --verify --deep --verbose=2 --strict "${DMG_DIR}/${DMG_NAME}" 2>&1 >/dev/null)"
-	if [ $? -eq 0 ]; then
-		echo "The disk image is now codesigned"
-	else
-		echo "The signature seems invalid${NC}"
-		exit 1
-	fi
+    echo "Codesign started"
+    codesign --deep --force --verbose \
+        --options runtime \
+        --timestamp \
+        -s "${SIGNATURE}" "${DMG_DIR}/${DMG_NAME}"
+
+    dmgsignaturecheck="$(codesign --verify --deep --verbose=2 --strict "${DMG_DIR}/${DMG_NAME}" 2>&1 >/dev/null)"
+    if [ $? -eq 0 ]; then
+        echo "The disk image is now codesigned"
+    else
+        echo "The signature seems invalid${NC}"
+        exit 1
+    fi
 fi
+
 
 if [[ -n "${NOTARIZE}" && "${NOTARIZE}" != "-null-" ]]; then
 	echo "Notarization started"
